# gpus: 1
hop_length: 512
sequence_length: 327680
sampling_rate: 16000
data_root: './dataset'
checkpoint_path: 'weights/attempt-1.ckpt' # will be ignored in train.py



        
dataloader:
    batch_size: 4
    num_workers: 8
    shuffle: False
    pin_memory: True
        
task:
    frame_threshold: 0.8 
#  trainer:
#     gpus: ${gpus}
    
defaults:
    - model: ClassifierFreeLatentRoll
    - task: generation
    - dataset: Sampling